apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169888554
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169888554
    app.kubernetes.io/part-of: test-app-169888554
  name: java-quarkus-169888554
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169888554
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169888554
    spec:
      containers:
      - image: quay.io/hacdev/vyi99i9z-tenant/test-app-169888554/java-quarkus-169888554@sha256:3b5d046f3d1478c547c1111d38c2b44d84ee522722ac73dde96b422bbe54d9f9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
