apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169888554
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/vyi99i9z-tenant/test-app-169888554/java-quarkus-169888554@sha256:3b5d046f3d1478c547c1111d38c2b44d84ee522722ac73dde96b422bbe54d9f9
        name: my-java-quarkus
        resources: {}
status: {}
